### ISSUE TITLE
allow copying system files to RAM

### ISSUE THREAD

**Issue by testbird** [graysky2/anything-sync-daemon#2]
With 16GB and more installed, /var and even /usr should easily fit into RAM.

To support this the startup scripts would just have to run really soon (initramfs even?), and the shutdown scripts really late, in the up/down sequence.

**Comment by nasenatmer** [comment]
I had `/var/log` included in my `WHATTOSYNC` array and had the problem that pacman would give me the following error when updating packages that included `/var/log` in them (like cups or systemd): `error: failed to commit transaction (conflicting files)` This was due to `/var/log` being a symlink instead of a dir.

Maybe I did something wrong there, but as soon as I stopped `asd` I could update the packages all fine.  See also [this thread](https://bbs.archlinux.org/viewtopic.php?id=193984) in the Arch forums.

**Comment by graysky2** [comment]
https://github.com/graysky2/anything-sync-daemon/issues/19

**Comment by testbird** [comment]
Hey, I now found USE_OVERLAYFS (mentioned above) in the wiki. :-)

If asd configures the overlayfs in the fstab, all is good, because sync/unsync happen at the right time without any additional risk of files beeing alredy open on creation or still open on shutdown.
Does it get configured in fstab?

**Comment by graysky2** [comment]
No need for fstab modification.  Asd does it instead of symlinking if your system supports it and if you enable it.

**Comment by testbird** [comment]
It leaves open a time window with another fs mounted to that path.
Only if asd is started imediately after, and stoped only imediately before fstab is handled would there be no risk. Don't know if systemd can ensure that.

**Comment by testbird** [comment]
I just had a simple idea that could get rid of all the start/stop contingencies:

Add an option to anything-sync-daemon to only do the aditional frequent syncs for overlay filesystems that the user (or some other tool) has set up in fstab.

**Comment by nasenatmer** [comment]
Thanks for the hint! I found this issue via google and didn't bother checking the other open issues in here. My bad!

**Comment by graysky2** [comment]
I have no immediate plans to begin to think about how to implement... since systemd runs at such a low level, I think doing so will be troublesome.
