### ISSUE TITLE
Since recently the usage of overlayfs turned using the daemon into a huge waste of space.

### ISSUE THREAD

**Issue by jschuck** [graysky2/anything-sync-daemon#26]
I was happy about the overlayfs change, since it was exactly what i wanted from using this daemon. Fast systemstartup and only the changed config files going into RAM while being read from SSD. Best of both worlds.

Recently however you introduced a double backup system basically double syncing the data on the drive to the X-backup_asd and X-back-ovfs folders. Doubling the space usage on the small SSD i use it on. In my case it's the home partition which was using around 25 Gigs of 50 before and now nears 40Gigs due to these folders.

Is there any chance we can get an option to turn that new behaviour off? I was hoping that the USE_BACKUPS option would help, but i was mistaken.

**Comment by graysky2** [comment]
There is no way to correctly implement the overlayfs mount without having
two copies on the file system since one is by definition, read-only and
thus cannot be modified while the mount is active.

On Monday, November 2, 2015, jschuck <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/graysky2/anything-sync-daemon/issues/26>.
>


-- 
Sent from Gmail Mobile

**Comment by jschuck** [comment]
Ah well. Worth a try. I'll just have to buy a bigger disk then. Thanks for the clarification.
