### ISSUE TITLE
Can I sync ~/.config ?

### ISSUE THREAD

**Issue by cathaysia** [graysky2/anything-sync-daemon#57]
Hello!
I want sync ~/.config so that I log on Gnome more faster. All my commands as following:
1. 
```shell
yay -S anthing-sync-daemon
```
2. Add /home/tea/.config to WHATTOSYNC
3. 
```shell
# systemctl enable asd
```
But when I reboot and log on Gnome, I found .config become empty.And I find asd in  `systemctl list-jobs`.
When I run `systemctl status asd`, it said "mv ....... .config already existed".

How can I sync .config?

**Comment by D-Nice** [comment]
I'm not answering this specific problem but the goal you're aiming towards.

It won't let you login any faster, only slower, because now rather than portions of your .config being loaded on log-on, you're slowing your bootup time majorly as now your full .config path with all its files have to be read from disk and loaded onto tmpfs (fair assumption you're using that if you want faster reads). This tool is better utilized by inspecting on your system, where lots of IO ops are occurring, using `lsof` or some other utilities, and syncing those specific directories. Improving overall performance, as now there's not an unnecessary overhead of countless of directories being added as well, which yield little to no benefit.

Trying to do this with .config as a whole is a whole 'nother can of worms, depending on your distro, which I'll leave to someone maybe more familiar with yours to answer. But to achieve this, you'd likely have to get this service up before any other services that may depend on what's in your .config, or else run into potential data races.

**Comment by cathaysia** [comment]
OK. Thanks your answer. I'm stupid on this question. It seems pointless that sync .config to tmpfs. May I should just install psd to boost firefox.

**Comment by D-Nice** [comment]
I am using ASD myself, to sync heavy IO paths, including some in my .config (not the whole .config though) and .cache, and also for browsers. PSD may be safer for browsers, but I haven't run into issues with ASD for them either.
