### ISSUE TITLE
clean command not working

### ISSUE THREAD

**Issue by afm0901x** [graysky2/anything-sync-daemon#79]
`# asd c` cannot find any **crashrecovery** dir to be removed.

after some debugging with `set -x`, I found out that `find` exited with
`find: warning: ‘-name’ matches against basenames only, but the given pattern contains a directory separator (‘/’), thus the expression will evaluate to false all the time.  Did you mean ‘-wholename’?`

and changing `-name` to `-wholename` fix the issue.
or should we give the **basename** instead?

https://github.com/graysky2/anything-sync-daemon/blob/19204c7fd227cd298f30b923f9b969d5d31f3e54/common/anything-sync-daemon.in#L351

**Comment by manorit2001** [comment]
I believe I had fixed it in https://github.com/graysky2/anything-sync-daemon/commit/1c5ae0cb3ac73f8b48a721d0554435af67b63058. Have you tried the latest build?

Remember to stop asd before upgrading if you are doing so manually. This update brings a major change of using bind mounts instead of symlinking which tries to solve some other issues also

**Comment by afm0901x** [comment]
latest build indeed fixed the issue, my bad
